[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Marker classifications
markers =
    critical: highly critical application flow tests
    unit: isolated unit tests
    integration: api and system integration tests

# Run options
addopts = --strict-markers -ra -v --tb=short
timeout = 30
